### ISSUE TITLE
グローバルのCSSの取り込み方が不明

### ISSUE THREAD

**Issue by JunyaAndooo** [JunyaAndooo/distribution-site-by-next#5]
reset.cssの取り込み方の調査

_app.jsでできるらしいが、tsにしたいかも

**Comment by sano-suguru** [comment]
> Global CSS cannot be imported from files other than your Custom <App>. Please move all global CSS imports to pages/_app.js.
> Read more: https://err.sh/next.js/css-global

**Comment by JunyaAndooo** [comment]
_app.tsxを追加して、そこでResset.cssを取り込みました
